export { default } from './PropertyEdit'
export { default as PropertyEdit } from './PropertyEdit'
export { default as DetailsTab } from './DetailsTab'
export { default as LocationTab } from './LocationTab'
export { default as LayoutTab } from './LayoutTab'
export { default as AmenitiesTab } from './AmenitiesTab'
export { default as PhotosTab } from './PhotosTab'
export { default as ServicesTab } from './ServicesTab'
export { default as RulesTab } from './RulesTab'
export { default as PricingTab } from './PricingTab'